### ISSUE TITLE
How to pass S3 credentials to s3proxy?

### ISSUE THREAD

**Issue by hirenoble** [gmoon/s3proxy#27]
I'm getting credentialsError while trying to run express-basic

**Comment by gmoon** [comment]
s3proxy uses the aws javascript sdk. You can provide credentials using any method supported:

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-node.html

The Environment Variables option is easy to get started, just make sure the variables are defined before you start the node process:

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-environment.html

One way to test is to verify that your aws cli works from command line:

`aws s3 ls s3://s3proxy-public/`

(substitute your bucket name)

**Comment by gmoon** [comment]
@hirenoble were you able to run the example? ok to close?

**Comment by gmoon** [comment]
Closing this. Added a Credentials section to the README: https://github.com/gmoon/s3proxy#credentials

If you need addition help please re-open the ticket.
